### ISSUE TITLE
hls.js configuration support

### ISSUE THREAD

**Issue by olivierEddie** [muxinc/videojs-mux-kit#49]
Are there any plans to make the hls.js implementation configurable? I'm particularly interested in being able to set `capLevelToPlayerSize`, to save bandwidth for mobile users not on wi-fi.

**Comment by cadavre** [comment]
1. Allowing to set Hls.js options would be great to finetune the playback options. So definitely +1 for this!
2. Would be also great is Hls.js player instance could be exposed somewhere so we can grab it and ie. use advanced event listeners.

**Comment by gkatsev** [comment]
This has been fixed in v0.11.0: https://github.com/muxinc/videojs-mux-kit/releases/tag/v0.11.0

It allows both the configuration and exposed hlsjs instance on the tech.
