### ISSUE TITLE
Issue with getComputedStyle, videos.js should be updated

### ISSUE THREAD

**Issue by peacepostman** [muxinc/videojs-mux-kit#60]
Hello,

We are having an issue with the progress bar on iOS. I've found that the issue has been fixed with the release of video.js v7.12.2, which is already pretty old. Is there a reason for videojs-mux-kit to be locked with the 7.12.1 version ?

Best regards,

**Comment by mmcc** [comment]
Thanks for the heads up! Did a big dependency pass in #61, so this should be good to go.
