### ISSUE TITLE
Use mux kit with alternative hls playback engine (VHS).

### ISSUE THREAD

**Issue by f3cp** [muxinc/videojs-mux-kit#62]
The readme mentions that hls.js is used as the playback engine due to 'some issues we've seen with the default Video.js playback engine and Mux streams'.

I would prefer to use the default 'VHS' plugin for HLS support with video.js as it is compatible with other plugins, most notably 'videojs-contrib-quality-levels' and I can use the VHS properties and events.

Is it possible to set the mux kit video.js to use VHS - or would I be better off just using a standard implementation of video.js and not using this kit at all.

Assuming it was the VHS implementation of HLS that had the issues with Mux streams that are mentioned, are these issues documented anywhere so I can evaluate whether it would be an acceptable risk for our use case?

**Comment by gkatsev** [comment]
With mux-kit 0.8.0, it's now possible to use this library with VHS. You'll want to change your import from `@mux/videojs-kit` to `@mux/videojs-kit/dist/index.vhs.js`.
Alternatively, if the only issue is integration with videojs-contrib-quality-levels, you can wait for #70.

**Comment by gkatsev** [comment]
this package now integrates hls.js with videojs-contrib-quality-levels as of version 0.9.0. So, you can choose whether you want hls.js or VHS playback assuming only videojs-contrib-quality-levels support is needed.
